version: '3'

services:
  postgres_dev:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data/postgres
    volumes:
       - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
       - ./data/pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    links:
      - postgres_dev
    depends_on:
      - postgres_dev

