version: '3'

services:
  # machine name_role(DEV)Number(1)
  lm_dev1:
    image: cassandra
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f'
    volumes:
      - ./data/lm_dev1:/var/lib/cassandra
    environment:
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=200M
      # bind for outside connection
      - CASSANDRA_RPC_ADDRES=192.168.0.101
    ports:
      - "9042:9042"
      - "9160:9160"
    ulimits:
      # use  memlock: -1 for unlim
      memlock: 6291456
      nproc: 32768
      nofile: 100000