version: '3'

services:
  neo4j_cluster1_dev:
    image: neo4j
    ports:
      - "7474:7474"
      - "6477:6477"
      - "7687:7687"
    environment:
      # not used due out of memory error
      #- NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      #- NEO4J_apoc_import_file_enabled=true
      #- NEO4J_dbms_shell_enabled=true
      #- NEO4J_dbms_memory_pagecache_size=4G
      #- NEO4J_dbms_memory_heap_max__size=8G
      #- NEO4J_dbms_memory_heap_initial__size=8G
      #- NEO4J_dbms_tx__log_rotation_retention__policy=3G size
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes      
      - NEO4J_causalClustering_expectedCoreClusterSize=2
      - NEO4J_causalClustering_initialDiscoveryMembers=neo4j_cluster1_dev:5000,neo4j_cluster2_dev:5000
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
    volumes:
      - ./data/cluster1/plugins:/plugins
      - ./data/cluster1/logs:/logs
      - ./data/cluster1/data:/data
      - ./data/cluster1/import:/import
      - ./data/cluster1/conf:/conf
    ulimits:
      # use  memlock: -1 for unlim
      memlock: 6291456
      nproc: 32768
      nofile: 100000
  neo4j_cluster2_dev:
    image: neo4j
    ports:
      - "7475:7475"
      - "6478:6478"      
      - "7688:7688" 
    environment:
      # not used due out of memory error
      #- NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      #- NEO4J_apoc_import_file_enabled=true
      #- NEO4J_dbms_shell_enabled=true
      #- NEO4J_dbms_memory_pagecache_size=4G
      #- NEO4J_dbms_memory_heap_max__size=8G
      #- NEO4J_dbms_memory_heap_initial__size=8G
      #- NEO4J_dbms_tx__log_rotation_retention__policy=3G size
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes      
      - NEO4J_causalClustering_expectedCoreClusterSize=2
      - NEO4J_causalClustering_initialDiscoveryMembers=neo4j_cluster1_dev:5000,neo4j_cluster2_dev:5000
      - NEO4J_dbms_connector_http_listen__address=:7475
      - NEO4J_dbms_connector_https_listen__address=:6478
      - NEO4J_dbms_connector_bolt_listen__address=:7688
    volumes:
      - ./data/cluster2/plugins:/plugins
      - ./data/cluster2/logs:/logs
      - ./data/cluster2/data:/data
      - ./data/cluster2/import:/import
      - ./data/cluster2/conf:/conf
    ulimits:
      # use  memlock: -1 for unlim
      memlock: 6291456
      nproc: 32768
      nofile: 100000

  neo4j_replica_dev:
    image: neo4j
    ports:
      - "7476:7476"
      - "6479:6479"      
      - "7689:7689"
    environment:
      - NEO4J_dbms_mode=READ_REPLICA
      - NEO4J_causalClustering_initialDiscoveryMembers=neo4j_cluster1_dev:5000,neo4j_cluster2_dev:5000
      - NEO4J_dbms_connector_http_listen__address=:7476
      - NEO4J_dbms_connector_https_listen__address=:6479      
      - NEO4J_dbms_connector_bolt_listen__address=:7689
    volumes:
      - ./data/replica/plugins:/plugins
      - ./data/replica/logs:/logs
      - ./data/replica/data:/data
      - ./data/replica/import:/import
      - ./data/replica/conf:/conf