version: '3'

services:
  redisdb_dev:
    image: redis
    ports: 
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis_commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redisdb_dev:6379
    ports:
      - "8091:8081"
    links:
      - redisdb_dev
    depends_on:
      - redisdb_dev