version: '3'

services:
  lm_kafka_dev:
    image: wurstmeister/kafka
    depends_on:
      - lm_zoo_dev
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://lm_kafka_dev:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=lm_zoo_dev:2181

  lm_zoo_dev:
    image: zookeeper
    ports:
      - "2181:2181"

  schema_registry:
    image: confluentinc/cp-schema-registry
    depends_on:
      - lm_zoo_dev
      - lm_kafka_dev
    ports:
      - "8081:8081"
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema_registry
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL="lm_zoo_dev:2181"
      
  rest-proxy:
    image: confluentinc/cp-kafka-rest
    depends_on:
      - lm_kafka_dev
      - lm_zoo_dev
    links:
      - lm_kafka_dev
      - schema_registry
    ports:
      - "8082:8082"
    environment:
      - KAFKA_REST_HOST_NAME=rest-proxy
      - KAFKA_REST_BOOTSTRAP_SERVERS="lm_kafka_dev:9092"
      - KAFKA_REST_LISTENERS=http://0.0.0.0:8082
      - KAFKA_REST_SCHEMA_REGISTRY_URL=http://schema_registry:8081
