version: '3'

services:

  mongo_dev:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
      - ./data/logs:/data/logs
    command: mongod --smallfiles

  mongo_express:
    image: mongo-express
    ports:
      - "8089:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo_dev
    links:
      - mongo_dev