version: '3'

services:
  lm_kafka1_dev:
    image: wurstmeister/kafka
    depends_on:
      - lm_zoo1_dev
      - lm_zoo2_dev
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://lm_kafka1_dev:9092
      - KAFKA_ZOOKEEPER_CONNECT=lm_zoo1_dev:2181,lm_zoo2_dev:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
  
  lm_kafka2_dev:
    image: wurstmeister/kafka
    depends_on:
      - lm_zoo1_dev
      - lm_zoo2_dev
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://lm_kafka2_dev:9093
      - KAFKA_ZOOKEEPER_CONNECT=lm_zoo1_dev:2181,lm_zoo2_dev:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093

  lm_zoo1_dev:
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=lm_zoo1_dev:2888:3888 server.2=lm_zoo2_dev:2888:3888

  lm_zoo2_dev:
    image: zookeeper
    ports:
      - "2182:2181"
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=lm_zoo1_dev:2888:3888 server.2=lm_zoo2_dev:2888:3888
