version: '3'

services:
  db_dev:
    image: redis
    ports: 
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes

  redis_commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:db_dev:6379
    ports:
      - "8091:8081"
    links:
      - db_dev
    depends_on:
      - db_dev